# Generated by Django 5.1.2 on 2024-10-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Despesas',
            new_name='Despesa',
        ),
        migrations.AlterModelTable(
            name='despesa',
            table='despesas',
        ),
    ]
